/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Conexao.ConexaoBD;
import Dao.UsuarioDao;
import Controller.UsuarioController;
import Dao.CreditoDao;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.UnsupportedEncodingException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Home
 */
public class UsuarioEditarForm extends javax.swing.JDialog {
     ConexaoBD conexao = new ConexaoBD();
    UsuarioDao usuariosdao = new UsuarioDao();
    UsuarioController usuarios = new UsuarioController();
    private DefaultTableModel modelo = new DefaultTableModel();
    private String novasenha="";
    private String senhaAtinga="";
    public int idusuario;
    public int idlogado;
    private boolean eadm=false;
    public int retorno=0;
    /**
     * Creates new form UsuarioEditarForm1
     */
    public UsuarioEditarForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         LiberarCampos();
        txtId.setEnabled(false);
        this.setLocationRelativeTo(null);

    }
    public void verCheckbox(int id){
        if(usuariosdao.temAcesso(id)==true){
            
            jcbxBloquear.setVisible(true);
        }else{
            
            jcbxBloquear.setVisible(false);
        }   
    }
        public void editarCampos(Integer id){
        usuarios.setIdusuario(id);
        int bloqueio=0;
        int administrador=0;
       
       UsuarioDao dao = new UsuarioDao();
      for (UsuarioController u : dao.CarregarUsuarios(id)) {
        txtId.setText(Integer.toString(u.getIdusuario()));
        txtNomeUsuario.setText(u.getNomeusuario());
        txtContatoUsuario.setText(u.getContatousuario());
        txtEmailUsuario.setText(u.getEmailusuario());
        bloqueio=u.getBloquear();
        administrador=u.getAdm();
        senhaAtinga=u.getSenhausuario();
        txtNomeUsuario.requestFocus();
        if(usuariosdao.temAcesso(idlogado)==true){
          if(bloqueio==1){
              jcbxBloquear.setSelected(true);
          }else{
              jcbxBloquear.setSelected(false);
          }

        }
    }}
            public boolean verificarCarmpos(){
       
        if(txtNomeUsuario.getText().equals("")|| txtContatoUsuario.getText().equals("") 
                || txtEmailUsuario.getText().equals("")){
            
           return true;
        }
       return false; 
    }
    public void SalvarUsuario() throws UnsupportedEncodingException{
         int tipo=0;
       usuarios.setIdusuario(Integer.parseInt(txtId.getText()));
       usuarios.setNomeusuario(txtNomeUsuario.getText().toUpperCase().trim());
       usuarios.setContatousuario(txtContatoUsuario.getText());
       usuarios.setEmailusuario(txtEmailUsuario.getText().toLowerCase().trim());
       if("".equals(novasenha)){
           usuarios.setSenhausuario(senhaAtinga);
       }else{
           usuarios.setSenhausuario(novasenha);
       }
       if(usuariosdao.temAcesso(idlogado)==true){
          tipo=0; 
           System.out.println("tipo: "+tipo);
                      usuarios.setAdm(0); 
                   if(jcbxBloquear.isSelected()){
                      usuarios.setBloquear(1); 
                   }else{
                      usuarios.setBloquear(0);
                   }
       }else{
           tipo=1; 
       }


       
        usuariosdao.AtualizarUsuario(usuarios,tipo);
        }
    public void limparCampos(){
          
            txtNomeUsuario.setText("");
            txtContatoUsuario.setText("");
            txtEmailUsuario.setText("");
          
    }
    public void LerCampos() {
         
         txtNomeUsuario.setEnabled(false);
         txtContatoUsuario.setEnabled(false);
         txtEmailUsuario.setEnabled(false);
      
         btnSalvar.setEnabled(false);
         //btnCancelar.setEnabled(false);
        ;
    }
        public void LiberarCampos() {
      
        txtNomeUsuario.setEnabled(true);
        txtContatoUsuario.setEnabled(true);
        txtEmailUsuario.setEnabled(true);
        
        txtNomeUsuario.requestFocus();
        btnSalvar.setEnabled(true);
        //btnCancelar.setEnabled(true); 
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JP_PRINCIPAL = new javax.swing.JPanel();
        lbNome = new javax.swing.JLabel();
        lbNomeOriginal = new javax.swing.JLabel();
        lbNomeOriginal1 = new javax.swing.JLabel();
        txtEmailUsuario = new javax.swing.JTextField();
        txtNomeUsuario = new javax.swing.JTextField();
        txtContatoUsuario = new javax.swing.JTextField();
        lbNomeOriginal3 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnAlterarSenha = new javax.swing.JButton();
        jcbxBloquear = new javax.swing.JCheckBox();
        btnSalvar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lbTitulo1 = new javax.swing.JLabel();
        lbFechar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JP_PRINCIPAL.setBackground(new java.awt.Color(255, 255, 255));
        JP_PRINCIPAL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 4));
        JP_PRINCIPAL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbNome.setBackground(new java.awt.Color(255, 255, 255));
        lbNome.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        lbNome.setForeground(new java.awt.Color(51, 51, 51));
        lbNome.setText("Contato");
        JP_PRINCIPAL.add(lbNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, 33));

        lbNomeOriginal.setBackground(new java.awt.Color(255, 255, 255));
        lbNomeOriginal.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        lbNomeOriginal.setForeground(new java.awt.Color(51, 51, 51));
        lbNomeOriginal.setText("Email");
        JP_PRINCIPAL.add(lbNomeOriginal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, 31));

        lbNomeOriginal1.setBackground(new java.awt.Color(255, 255, 255));
        lbNomeOriginal1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        lbNomeOriginal1.setForeground(new java.awt.Color(51, 51, 51));
        lbNomeOriginal1.setText("Id");
        JP_PRINCIPAL.add(lbNomeOriginal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        txtEmailUsuario.setFont(new java.awt.Font("Source Sans Pro ExtraLight", 0, 14)); // NOI18N
        txtEmailUsuario.setForeground(new java.awt.Color(102, 102, 102));
        txtEmailUsuario.setEnabled(false);
        txtEmailUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailUsuarioKeyPressed(evt);
            }
        });
        JP_PRINCIPAL.add(txtEmailUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 364, 47));

        txtNomeUsuario.setFont(new java.awt.Font("Source Sans Pro ExtraLight", 0, 14)); // NOI18N
        txtNomeUsuario.setForeground(new java.awt.Color(102, 102, 102));
        txtNomeUsuario.setEnabled(false);
        txtNomeUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeUsuarioKeyPressed(evt);
            }
        });
        JP_PRINCIPAL.add(txtNomeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 364, 47));

        txtContatoUsuario.setFont(new java.awt.Font("Source Sans Pro ExtraLight", 0, 14)); // NOI18N
        txtContatoUsuario.setForeground(new java.awt.Color(102, 102, 102));
        txtContatoUsuario.setEnabled(false);
        txtContatoUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtContatoUsuarioKeyPressed(evt);
            }
        });
        JP_PRINCIPAL.add(txtContatoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 364, 47));

        lbNomeOriginal3.setBackground(new java.awt.Color(255, 255, 255));
        lbNomeOriginal3.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        lbNomeOriginal3.setForeground(new java.awt.Color(51, 51, 51));
        lbNomeOriginal3.setText("Nome");
        JP_PRINCIPAL.add(lbNomeOriginal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 30));

        txtId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        JP_PRINCIPAL.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 128, 40));

        btnAlterarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Galeria/Icones1/if_Line_ui_icons_Svg-16_1465830.png"))); // NOI18N
        btnAlterarSenha.setText("Alterar Senha");
        btnAlterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarSenhaActionPerformed(evt);
            }
        });
        JP_PRINCIPAL.add(btnAlterarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        jcbxBloquear.setBackground(new java.awt.Color(255, 255, 255));
        jcbxBloquear.setForeground(new java.awt.Color(51, 51, 51));
        jcbxBloquear.setText("Bloquear");
        JP_PRINCIPAL.add(jcbxBloquear, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, -1, -1));

        btnSalvar.setBackground(new java.awt.Color(235, 114, 21));
        btnSalvar.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(51, 51, 51));
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        btnSalvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSalvarKeyPressed(evt);
            }
        });
        JP_PRINCIPAL.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 364, 50));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));

        lbTitulo1.setBackground(new java.awt.Color(255, 255, 255));
        lbTitulo1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        lbTitulo1.setForeground(new java.awt.Color(255, 255, 255));
        lbTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbTitulo1.setText("Alterar Cadastro de Administradores");

        lbFechar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbFechar.setForeground(new java.awt.Color(255, 255, 255));
        lbFechar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFechar.setText("X");
        lbFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbFecharMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbFecharMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbFecharMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lbTitulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(lbFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTitulo1)
                    .addComponent(lbFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        JP_PRINCIPAL.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 50));

        getContentPane().add(JP_PRINCIPAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailUsuarioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnSalvar.requestFocus();
        }
    }//GEN-LAST:event_txtEmailUsuarioKeyPressed

    private void txtNomeUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeUsuarioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtContatoUsuario.requestFocus();
        }
    }//GEN-LAST:event_txtNomeUsuarioKeyPressed

    private void txtContatoUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContatoUsuarioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtEmailUsuario.requestFocus();
        }
    }//GEN-LAST:event_txtContatoUsuarioKeyPressed

    private void btnAlterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarSenhaActionPerformed
        // TODO add your handling code here:
                if(usuariosdao.temAcesso(idlogado)==true){
                TrocarSenhaAdm troca = new TrocarSenhaAdm(this, true); 
                                
                                try {
                                    troca.setarSenhaAtual(Integer.parseInt(txtId.getText()));
                                } catch (SQLException ex) {
                                    Logger.getLogger(UsuarioEditarForm.class.getName()).log(Level.SEVERE, null, ex);
                                }
                                troca.setVisible(true);
                                int retorno=troca.getRetorno();
                                if(retorno==1){
                                    novasenha=troca.getSenhanova();
                                }
                }else{
          
                    TrocarSenhaUsu troca = new TrocarSenhaUsu(this, true);
                
                                try {
                                    troca.setarSenhaAtual(Integer.parseInt(txtId.getText()));
                                } catch (SQLException ex) {
                                    Logger.getLogger(UsuarioEditarForm.class.getName()).log(Level.SEVERE, null, ex);
                                }
                                troca.setVisible(true);
                                int retorno=troca.getRetorno();
                                if(retorno==1){
                                    novasenha=troca.getSenhanova();
                                }
                }
    }//GEN-LAST:event_btnAlterarSenhaActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(verificarCarmpos()){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos");
        }else{
            try {
                SalvarUsuario();
                retorno=1;
            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(UsuarioEditarForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.dispose();

        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnSalvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSalvarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if(verificarCarmpos()){
                JOptionPane.showMessageDialog(null, "Preencha todos os campos");
            }else{
                try {
                    SalvarUsuario();
                } catch (UnsupportedEncodingException ex) {
                    Logger.getLogger(UsuarioEditarForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                UsuarioListaForm usuariolista = null;
                try {
                    usuariolista = new UsuarioListaForm();
                } catch (SQLException ex) {
                    Logger.getLogger(UsuarioEditarForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                usuariolista.setVisible(true);
                this.dispose();

            }
        }
    }//GEN-LAST:event_btnSalvarKeyPressed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void lbFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbFecharMouseClicked
        //        System.exit(0);
        this.dispose();
    }//GEN-LAST:event_lbFecharMouseClicked

    private void lbFecharMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbFecharMouseEntered
        //        MatteBorder label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.yellow);
        //        lbFechar.setBorder(label_border);
        lbFechar.setForeground(Color.yellow);
    }//GEN-LAST:event_lbFecharMouseEntered

    private void lbFecharMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbFecharMouseExited
        //        MatteBorder label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        //        lbFechar.setBorder(label_border);
        lbFechar.setForeground(Color.white);
    }//GEN-LAST:event_lbFecharMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsuarioEditarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsuarioEditarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsuarioEditarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsuarioEditarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UsuarioEditarForm dialog = new UsuarioEditarForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JP_PRINCIPAL;
    private javax.swing.JButton btnAlterarSenha;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JCheckBox jcbxBloquear;
    private javax.swing.JLabel lbFechar;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbNomeOriginal;
    private javax.swing.JLabel lbNomeOriginal1;
    private javax.swing.JLabel lbNomeOriginal3;
    private javax.swing.JLabel lbTitulo1;
    private javax.swing.JTextField txtContatoUsuario;
    private javax.swing.JTextField txtEmailUsuario;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNomeUsuario;
    // End of variables declaration//GEN-END:variables
}
